INSERT INTO book (id, name, author, genre, language, page_count, min_age_restriction) VALUES (1, 'Harry Potter', 'Joanne Rowling', 'FICTION', 'ENGLISH', 560, 6);
INSERT INTO book (id, name, author, genre, language, page_count, min_age_restriction) VALUES (2, 'Lord of the rings', 'J. R. R. Tolkien', 'FICTION', 'ENGLISH', 300, 10);
INSERT INTO book (id, name, author, genre, language, page_count, min_age_restriction) VALUES (3, 'Pride and Prejudice', 'Jane Austen', 'DRAMA', 'ENGLISH', 300, 12);
INSERT INTO book (id, name, author, genre, language, page_count, min_age_restriction) VALUES (4, 'Jane Eyre', 'Charlotte Brontë', 'DRAMA', 'ENGLISH', 400, 10);
INSERT INTO book (id, name, author, genre, language, page_count, min_age_restriction) VALUES (5, 'Nausea', 'Jean-Paul Sartre', 'NOVEL', 'ENGLISH', 360, 16);
INSERT INTO book (id, name, author, genre, language, page_count, min_age_restriction) VALUES (6, 'Neverwhere', 'Neil Gaiman', 'MYSTERY', 'ENGLISH', 180, 6);
INSERT INTO book (id, name, author, genre, language, page_count, min_age_restriction) VALUES (7, 'American Gods', 'Neil Gaiman', 'MYSTERY', 'ENGLISH', 560, 6);
INSERT INTO book (id, name, author, genre, language, page_count, min_age_restriction) VALUES (8, 'Sherlock Holmes', 'Arthur Conan Doyle', 'DETECTIVE', 'ENGLISH', 560, 8);
INSERT INTO book (id, name, author, genre, language, page_count, min_age_restriction) VALUES (9, 'Murder on the Orient Express', 'Agatha Christie', 'DETECTIVE', 'ENGLISH', 120, 12);
INSERT INTO book (id, name, author, genre, language, page_count, min_age_restriction) VALUES (10, 'And then there were none', 'Agatha Christie', 'DETECTIVE', 'ENGLISH', 106, 12);
INSERT INTO book (id, name, author, genre, language, page_count, min_age_restriction) VALUES (11, 'It', 'Stephen King', 'HORROR', 'ENGLISH', 423, 16);
INSERT INTO book (id, name, author, genre, language, page_count, min_age_restriction) VALUES (12, 'The shining', 'Stephen King', 'HORROR', 'ENGLISH', 350, 16);
INSERT INTO book (id, name, author, genre, language, page_count, min_age_restriction) VALUES (13, 'Carrie', 'Stephen King', 'HORROR', 'ENGLISH', 378, 16);
INSERT INTO book (id, name, author, genre, language, page_count, min_age_restriction) VALUES (14, 'Misery', 'Stephen King', 'DRAMA', 'ENGLISH', 320, 16);
INSERT INTO book (id, name, author, genre, language, page_count, min_age_restriction) VALUES (15, 'The green mile', 'Stephen King', 'MYSTERY', 'ENGLISH', 560, 16);
INSERT INTO book (id, name, author, genre, language, page_count, min_age_restriction) VALUES (16, 'The dark tower', 'Stephen King', 'MYSTERY', 'ENGLISH', 220, 16);
INSERT INTO book (id, name, author, genre, language, page_count, min_age_restriction) VALUES (17, 'The dead zone', 'Stephen King', 'HORROR', 'ENGLISH', 289, 16);
INSERT INTO book (id, name, author, genre, language, page_count, min_age_restriction) VALUES (18, 'Fight club', 'Chuck Palahniuk', 'DRAMA', 'ENGLISH', 152, 18);
INSERT INTO book (id, name, author, genre, language, page_count, min_age_restriction) VALUES (19, 'One Flew Over the Cuckoo''s Nest', 'Ken Kesey', 'NOVEL', 'ENGLISH', 150, 18);
INSERT INTO book (id, name, author, genre, language, page_count, min_age_restriction) VALUES (20, 'War and Peace', 'Leo Tolstoy', 'NOVEL', 'ENGLISH', 1560, 16);
INSERT INTO book (id, name, author, genre, language, page_count, min_age_restriction) VALUES (21, 'Fathers and Sons', 'Ivan Turgenev', 'NOVEL', 'ENGLISH', 143, 12);
INSERT INTO book (id, name, author, genre, language, page_count, min_age_restriction) VALUES (22, 'First Love', 'Ivan Turgenev', 'NOVEL', 'ENGLISH', 60, 12);
INSERT INTO book (id, name, author, genre, language, page_count, min_age_restriction) VALUES (23, 'Dead Souls', 'Nikolai Gogol', 'NOVEL', 'ENGLISH', 120, 10);
INSERT INTO book (id, name, author, genre, language, page_count, min_age_restriction) VALUES (24, 'To kill a mockingbird', 'Harper Lee', 'DRAMA', 'ENGLISH', 400, 16);
INSERT INTO book (id, name, author, genre, language, page_count, min_age_restriction) VALUES (25, '1984', 'George Orwell', 'NOVEL', 'ENGLISH', 200, 16);
INSERT INTO book (id, name, author, genre, language, page_count, min_age_restriction) VALUES (26, 'The Book Thief', 'Markus Zusak', 'DRAMA', 'ENGLISH', 560, 16);
INSERT INTO book (id, name, author, genre, language, page_count, min_age_restriction) VALUES (27, 'Brave New World', 'Aldous Huxley', 'FICTION', 'ENGLISH', 623, 16);
INSERT INTO book (id, name, author, genre, language, page_count, min_age_restriction) VALUES (28, 'The Call of the Wild', 'Jack London', 'ADVENTURE', 'ENGLISH', 400, 8);
INSERT INTO book (id, name, author, genre, language, page_count, min_age_restriction) VALUES (29, 'Fahrenheit 451', 'Ray Bradbury', 'DRAMA', 'ENGLISH', 320, 12);
INSERT INTO book (id, name, author, genre, language, page_count, min_age_restriction) VALUES (30, 'Love in the Time of Cholera', 'Gabriel García Márquez', 'DRAMA', 'ENGLISH', 600, 10);
INSERT INTO book (id, name, author, genre, language, page_count, min_age_restriction) VALUES (31, 'The Lovely Bones', 'Alice Sebold', 'DRAMA', 'ENGLISH', 280, 12);
INSERT INTO book (id, name, author, genre, language, page_count, min_age_restriction) VALUES (32, 'The Great Gatsby', 'F. Scott Fitzgerald', 'NOVEL', 'ENGLISH', 360, 12);
INSERT INTO book (id, name, author, genre, language, page_count, min_age_restriction) VALUES (33, 'The Little Prince', 'Antoine de Saint-Exupéry', 'ADVENTURE', 'ENGLISH', 60, 6);
INSERT INTO book (id, name, author, genre, language, page_count, min_age_restriction) VALUES (34, 'A Brief History of Time', 'Stephen Hawking', 'SCIENCE', 'ENGLISH', 560, 18);
INSERT INTO book (id, name, author, genre, language, page_count, min_age_restriction) VALUES (35, 'Don Quixote', 'Miguel de Cervantes`', 'ADVENTURE', 'ENGLISH', 560, 6);
